export const FETCH_PROFILE = "BNB/Profile/FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "BNB/Profile/FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "BNB/Profile/FETCH_PROFILE_FAILURE";

export const UPDATE_PROFILE = "BNB/Profile/UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "BNB/PUPDATEe/FETCH_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "BNB/Profile/UPDATE_PROFILE_FAILURE";
