export const FETCH_CINEMAS = "BNB/Cinemas/FETCH_CINEMAS";
export const FETCH_CINEMAS_SUCCESS = "BNB/Cinemas/FETCH_CINEMAS_SUCCESS";
export const FETCH_CINEMAS_FAILURE = "BNB/Cinemas/FETCH_CINEMAS_FAILURE";

export const ADD_CINEMA = "BNB/Cinemas/ADD_CINEMA";
export const ADD_CINEMA_SUCCESS = "BNB/Cinemas/ADD_CINEMA_SUCCESS";
export const ADD_CINEMA_FAILURE = "BNB/Cinemas/ADD_CINEMA_FAILURE";

export const DELETE_CINEMA = "BNB/Cinemas/DELETE_CINEMA";
export const DELETE_CINEMA_SUCCESS = "BNB/Cinemas/DELETE_CINEMA_SUCCESS";
export const DELETE_CINEMA_FAILURE = "BNB/Cinemas/DELETE_CINEMA_FAILURE";

export const UPDATE_CINEMA_BY_ID = "BNB/Cinemas/UPDATE_CINEMA_BY_ID";
export const UPDATE_CINEMA_BY_ID_SUCCESS = "BNB/Cinemas/UPDATE_CINEMA_BY_ID_SUCCESS";
export const UPDATE_CINEMA_BY_ID_FAILURE = "BNB/Cinemas/UPDATE_CINEMA_BY_ID_FAILURE";
