export const FETCH_USER_TICKETS = "BNB/Cinemas/FETCH_USER_TICKETS";
export const FETCH_USER_TICKETS_SUCCESS =
  "BNB/Cinemas/FETCH_USER_TICKETS_SUCCESS";
export const FETCH_USER_TICKETS_FAILURE =
  "BNB/Cinemas/FETCH_USER_TICKETS_FAILURE";

export const ADD_USER_TICKET = "BNB/Cinemas/ADD_USER_TICKET";
export const ADD_USER_TICKET_SUCCESS = "BNB/Cinemas/ADD_USER_TICKET_SUCCESS";
export const ADD_USER_TICKET_FAILURE = "BNB/Cinemas/ADD_USER_TICKET_FAILURE";
